== Quality goals

[discrete]
=== Example: Efficient scaling [[ref_goal_scaling, efficient scaling]]
The system should automatically scale up/down depending on user traffic (or migration traffic) and avoid resource waste
("no idle infrastructure"). This is mandatory to fulfil the commercial goals of the re-purchase. 

[discrete]
=== Example: Minimal run efforts [[ref_goal_run, minimal run efforts]]
Deployment and run mechanisms are automated so that lifecycle management of the application gets regular business.
Server-side security patches are rolled out potentially every week, patches and minor releases don´t need downtimes.
New major releases including new features in all client apps are planned 4 times a year and should follow NextCloud
product cycle not later than a month after public availability of NextCloud Enterprise major release. Client apps
could be patches and published on demand. Automation also includes automated consistency or health checking of applied
customisations.
