=== Debt: No unittest coverage for customizings(example)
The customizing team has not managed to implement unittests accompanying their development.

.Consequences
- the reduction to blackbox testing (= clicktests from outside the system) gives no picture
  about the base quality of the delivered changes

- many rainy day scenarios with separate code pathes are completely untested

- there are no automated unit testsuite (whitebox) with relevant code coverage for user interface
  and client customisation parts. (Some business logic parts have as a role model.)

- There is no Continuous Integration Pipeline that forces code formatting, linting and automated testing
  for newly produced code and ensures a quality baseline.

.Recommendation: 
This shortcoming has been addressed regularly from architecture, but no progress yet.
Frontend/client development still fully relies on high-level blackbox testing (Selenium and manual).
It is urgently recommended that the project or the following application management is catching up with
the whitebox testing shortcoming to reach the goal of release-robustness.

=== Risk: Underestimated traffic prediction(example)
Measurements on production indicate that the real traffic is by factor 2-3 higher thatn in the customer
prediction.

.Probability:
80%

.Mitigation:
* We use multiple load balancer in auto-scaler to handle mor traffic and distribute it better.
* Mid-term, we have to switch to a NoSQL implementation to remove DB bottleneck.

[TIP]
====
Never put a risk as primary concern in a customer meeting, always bring multiple mitigations.
Architects can bring up new risks without mitigations endlessly, but this is a form of doomsaying.
====