// == Tips, tricks, tools faq

The following sections help to use asciidoc and are an example how this chapter could be helpful at the same time.

=== Asciidoc, AsciiDoctor

==== Generate/debug doc generation with asciidoctor
You need at least Asciidoctor PDF (https://docs.asciidoctor.org/asciidoctor/latest/install/[install instructions]) and 
Asciidoctor (https://docs.asciidoctor.org/asciidoctor/latest/install/[install instructions]) to run the following 
commands successful.

E.g. under Ubuntu, install the following packages
----
sudo apt-get install asciidoctor ruby-asciidoctor-pdf
----

.html
As working commandline call for `asciidoctor` to trace doc generation is:
----
cd arcdoc-template
asciidoctor -b html5 -a imagesdir="../../../images" -a fontsdir="../../../stylesdir"\
 -a linkcss -a stylesdir="../../../themes/telefluid" -a stylesheet="telefluid.css"\
 --trace --verbose --destination-dir=gen/en/html --trace src/en/architecture-book.adoc
----

.pdf
As working commandline call for `asciidoctor-pdf` to trace doc generation is:
----
cd arcdoc-template
asciidoctor-pdf -a toc --destination-dir="gen/en/pdf" -a imagesdir=../../images\
 -a pdf-fontsdir="themes/telefluid-pdf" -a pdf-themesdir="themes/telefluid-pdf" -a pdf-theme="telefluid-pdf"\
 --trace --verbose src/en/architecture-book.adoc
----

=== Version number and date based on Git tags
The template automatically uses the values for `refnumber` and `refdate` from the values in `about.adoc`.
It is possible to use metadata from a branch or a tag instead via commandline and set the values during generation.

.Example
Assume that we always want to generate with the latest tag and the tag creation date. Assume that version tags look 
like `v12.34.567` and start with v:
----
alias arcnumber="git tag | grep 'v' | sort -r | head -1"
alias arcdate="git log -q --tags='v*' -1 --date=short |grep -E 'Date:\s*[0-9]*-[0-9]*-[0-9]*' |grep -oE\
    '[0-9]*-[0-9]*-[0-9]*'"
----

.html
As working commandline call for `asciidoctor` to trace doc generation is:
----
cd arcdoc-template
asciidoctor -b html5 -a imagesdir="../../../images" -a fontsdir="../../../stylesdir"\
 -a linkcss -a stylesdir="../../../themes/telefluid" -a stylesheet="telefluid.css"\
 -a revdate="$(arcdate)" -a revnumber=", $(arcnumber)"\
 --destination-dir=gen/en/html src/en/\
 --trace --verbose src/en/architecture-book.adoc
----

.pdf
----
cd arcdoc-template
asciidoctor-pdf -a toc --destination-dir="gen/en/pdf" -a imagesdir=../../images\
 -a pdf-fontsdir="themes/telefluid-pdf" -a pdf-themesdir="themes/telefluid-pdf" -a pdf-theme="telefluid-pdf"\
 -a revdate="$(arcdate)" -a revnumber=", $(arcnumber)"\
 --trace --verbose src/en/architecture-book.adoc
----

=== Asciidoc in VScode
It is recommended to use the following extension in VScode for docs-as-code:

-  https://github.com/asciidoctor/asciidoctor-vscode[AsciiDoc extension]

-  https://github.com/streetsidesoftware/vscode-spell-checker[Code Spell Checker extension supporting AsciiDoc]


To make preview for images working in VScode, add some lines to `settings.json` for User:
----
"[asciidoc]": {
    "editor.rulers": [120]
},
"asciidoc.preview.attributes": {
    "imagesdir": "${workspaceFolder}/images",
    "fontsdir": "${workspaceFolder}/themes/telefluid",
    "stylesdir": "${workspaceFolder}/themes/telefluid",
    "stylesheet": "telefluid.css", 
    "linkcss": "",
},
"asciidoc.preview.useEditorStyle": false,
"asciidoc.trace": "verbose",
"asciidoc.asciidoctorpdf_command": "asciidoctor-pdf -a pdf-fontsdir='${workspaceFolder}/themes/telefluid-pdf' -a pdf-themesdir='${workspaceFolder}/themes/telefluid-pdf' -a pdf-theme=telefluid-pdf --destination-dir='${workspaceFolder}/gen/pdf' --trace --verbose",
"asciidoc.use_asciidoctorpdf": true,
----

=== Solve draw.io SVG and formatted labels problem
We use the open tool draw.io (either on internet of via https://mywiki.telekom.de embedded in pages there as advanced
element option). The diagrams should be exported as SVG for optimal scalability.

When generating documentation, the diagram sometimes shows not up properly in pdf with an image-embedded error
*Viewer does not support full SVG 1.1* This means your diagrams requires reformatting as described here:
https://desk.draw.io/support/solutions/articles/16000042487-why-text-in-exported

[IMPORTANT]
To really disable the options for all elements, you sometimes have to explicitly check/uncheck the checkboxes until the
svg warning disappears!

=== GIT

==== Create repos with different master branch

.One time solution
----
git init --initial-branch=trunk
git init -b trunk
----

.Permanent rename default branch
----
git config --global init.defaultBranch trunk
----

.Existing repos
----
git branch -m trunk
----


==== Using GIT in case of certificate problems
Sometimes (esp. with MagentaCICD), there could be a (temporary) certificate verification problem. Every git command
shows a certificate error message then like:

.GIT certificate error
----
fatal: unable to access 'https://gitlab.devops.telekom.de/xxx': server certificate verification failed. 
CAfile: none CRLfile: non
----

To circumvent this, in worst case, do the following:

.Disable certificate check
----
GIT_SSL_NO_VERIFY=true git clone https://gitlab.devops.telekom.de/xxx
cd xxx
git config http.sslVerify false
----